[package]
name = "meshopt-decoder"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leb128 = "0.2.5"

[dev-dependencies]
criterion = "0.3.6"

[[bench]]
name = "bench"
harness = false